#Deployment to create new ReplicaSets for the python-hello pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello
spec:
  replicas: 2 #Number of replica pods
  selector:
    matchLabels:
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
        - name: python-hello
          image: qafro/python-hello:v1 #image of hello python
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000 #Pod port number
