#The service python-hello is implemented and traffic from the external load balancer is directed at the backend Pods.
apiVersion: v1
kind: Service
metadata:
  name: python-hello #Name of the service
spec:
  selector:
    app: python-hello 
  ports:
  - port: 5000
    targetPort: 5000  #Service port 
  type: LoadBalancer  #Type Loadbalancer to use

    
    
